# Generated by Django 3.1.1 on 2020-10-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('idMensaje', models.AutoField(primary_key=True, serialize=False)),
                ('Mensaje', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('NombreUsuario', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=15)),
                ('Telefono', models.IntegerField(max_length=12)),
            ],
        ),
    ]
