# Generated by Django 3.1.1 on 2020-10-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='Nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='Mensaje',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='NombreUsuario',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Password',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Telefono',
            field=models.IntegerField(unique=True),
        ),
    ]
