# Generated by Django 3.1.1 on 2020-10-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0002_auto_20201004_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='Status',
            field=models.IntegerField(default=1),
        ),
    ]
