# Generated by Django 3.1.1 on 2020-10-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0003_mensajes_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamentos',
            old_name='id',
            new_name='id_Departamento',
        ),
        migrations.AddField(
            model_name='mensajes',
            name='id_Departamento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='id_Departamento',
            field=models.IntegerField(default=0),
        ),
    ]
