# Generated by Django 3.1.1 on 2020-10-07 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0004_auto_20201005_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='Ip',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='id_Departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectowebApp.departamentos'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_Departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectowebApp.departamentos'),
        ),
    ]
