# Generated by Django 3.1.1 on 2020-10-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0005_auto_20201007_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajes',
            old_name='Status',
            new_name='Status_recibido',
        ),
        migrations.AddField(
            model_name='mensajes',
            name='Status_respuesta',
            field=models.IntegerField(default=2),
        ),
    ]
