# Generated by Django 3.1.2 on 2020-10-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0006_auto_20201016_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajes',
            old_name='id_Departamento',
            new_name='id_Departamento_id',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='id_Departamento',
            new_name='id_Departamento_id',
        ),
    ]
