# Generated by Django 3.1.2 on 2020-10-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0007_auto_20201022_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajes',
            old_name='id_Departamento_id',
            new_name='id_Departamento',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='id_Departamento_id',
            new_name='id_Departamento',
        ),
    ]
