# Generated by Django 3.1.2 on 2020-10-23 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0008_auto_20201022_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajes',
            old_name='id_Departamento',
            new_name='id_departamento',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='id_Departamento',
            new_name='id_departamento',
        ),
    ]
