# Generated by Django 3.1.2 on 2020-11-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectowebApp', '0009_auto_20201023_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='id_departamento',
            field=models.IntegerField(default=0),
        ),
    ]
